apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-otel-agent-deployment
  labels:
    app: nodejs-otel-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-otel-agent
  template:
    annotations:
      instrumentation.opentelemetry.io/inject-nodejs: "true"

    metadata:
      labels:
        app: nodejs-otel-agent
    spec:
      containers:
        - name: nodejs-otel-agent
          image: leonardozwirtes/nodejs-otel-agent:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: OTEL_SERVICE_NAME
              value: "nodejs-otel-agent"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=nodejs-otel-agent,environment=prd"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://opentelemetrycollector.monitoring.svc.cluster.local:4318"
