apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-otel-agent-deployment
  labels:
    app: nodejs-otel-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-otel-agent
  template:
    metadata:
      labels:
        app: nodejs-otel-agent
    spec:
      initContainers:
        - name: init-otel-agent
          image: node:20
          command: ["sh", "-c"]
          args:
            [
              "mkdir -p /otel-agent && cd /otel-agent && npm init -y && npm install otel-agent-nodejs --save && cp -r ./node_modules/otel-agent-nodejs/* /otel-agent",
            ]
          volumeMounts:
            - name: otel-agent-volume
              mountPath: /otel-agent

      containers:
        - name: nodejs-otel-agent
          image: leonardozwirtes/nodejs-otel-agent:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_OPTIONS
              value: "--require /otel-agent"
            - name: OTEL_SERVICE_NAME
              value: "nodejs-otel-agent"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://opentelemetrycollector.default.svc.cluster.local:4318/v1/traces"
            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: "http://opentelemetrycollector.default.svc.cluster.local:4318/v1/metrics"
          volumeMounts:
            - name: otel-agent-volume
              mountPath: /otel-agent
      volumes:
        - name: otel-agent-volume
          emptyDir: {}
